#!/bin/bash

#JSON_FILENAME=default-planck.json
JSON_FILENAME=default-60-percent.json
#JSON_FILENAME=68keys-io.json
python3 keycad.py kle_layouts/${JSON_FILENAME}
kinet2pcb -i keycad.net -w
kinjector --from keycad-kinjector.json --to keycad.kicad_pcb
python3 draw_outline.py
xdg-open keycad.kicad_pcb